import { Database, PaintBucket, Server, Terminal } from "lucide-react";
import { useState } from "react";

export default function AboutPage() {
  return (
    <div className="flex items-center justify-center shadow-md">
      <div className="max-w-4xl bg-white rounded-2xl shadow-lg border border-gray-200 p-10 space-y-8">
        {/* 상단 섹션 */}
        <div className="flex flex-col md:flex-row items-center">
          {/* 자기소개 */}
          <div className="space-y-6 md:w-1/2">
            <h1 className="text-4xl font-bold text-gray-900 font-pretendard">
              안녕하세요! 👋
            </h1>
            <p className="text-lg text-gray-700 leading-relaxed font-pretendard">
              저는{" "}
              <span className="font-semibold text-indigo-600">
                한양사이버대학교
              </span>
              <span className="font-semibold text-indigo-600">
                {" "}
                컴퓨터공학부
              </span>{" "}
              4학년입니다. 졸업 프로젝트로{" "}
              <span className="font-semibold text-indigo-600">
                학습 보조 웹 어플리케이션
              </span>
              을 개발하고 있어요. 카드를 작성하고 일정 기간마다 자동으로 복습할
              수 있도록 도와주는 웹어플리케이션입니다.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 font-pretendard">
              🎯 프로젝트 개요
            </h2>
            <p className="text-lg text-gray-700 font-pretendard">
              사용자가 카드를 만들고, 일정 기간 반복적으로 학습할 수 있는
              <span className="font-semibold text-indigo-600">
                {" "}
                스마트 학습 관리 웹 서비스
              </span>
              를 만들고 있습니다.
            </p>

            <h3 className="text-xl font-semibold text-gray-900 font-pretendard">
              🛠 구현 기능과 기술 스택
            </h3>
            <ul className="list-disc pl-5 space-y-2 text-gray-700 font-pretendard">
              <li className="flex items-center space-x-2">
                <Server className="w-5 h-5 text-blue-500" />
                <span>프론트엔드 : React + TailwindCSS</span>
              </li>
              <li className="flex items-center space-x-2">
                <Terminal className="w-5 h-5 text-gray-700" />
                <span>백엔드 : NodeJS + Remix</span>
              </li>
              <li className="flex items-center space-x-2">
                <Database className="w-5 h-5 text-green-600" />
                <span>데이터베이스 : SQLite를 활용한 데이터 관리</span>
              </li>
              <li className="flex items-center space-x-2">
                <PaintBucket className="w-5 h-5 text-indigo-500" />
                <span>Lucide Icons을 이용한 깔끔한 UI</span>
              </li>
            </ul>
          </div>

          {/* 아바타 이미지 */}
          <div className="flex justify-center md:w-1/2 relative">
            <div className="relative w-48 h-48 md:w-64 md:h-64">
              <div className="absolute inset-0 bg-gray-300 rounded-full blur-sm opacity-30"></div>
              <img
                src="/avatar.gif"
                alt="Avatar"
                className="w-full h-full rounded-full object-cover border-4 border-white shadow-lg"
              />
              <p className="text-xs text-gray-500 text-center mt-2">
                This image was generated by DALL·E.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
